# Generated by Django 5.1.1 on 2025-06-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_special_case',
            field=models.BooleanField(default=False),
        ),
    ]
